version: '3.9'

services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${GLUETUN_BITTORRENT_PORT:-6881}:6881"
      - "${GLUETUN_BITTORRENT_PORT:-6881}:6881/udp"
      - "${QBITTORRENT_PORT:-8085}:8085"
    volumes:
      - ${DOCKER_VOLUMES_PATH}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - TZ=${TZ:-UTC}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CATEGORIES=${SERVER_CATEGORIES}
      - UPDATER_PERIOD=${UPDATER_PERIOD:-24h}
      - DOT=${DOT:-off}
      - DOT_PROVIDERS=${DOT_PROVIDERS:-cloudflare}
      - DNS_ADDRESS=${DNS_ADDRESS:-127.0.0.1}
      - FIREWALL_VPN_INPUT_PORTS=${GLUETUN_BITTORRENT_PORT:-6881}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.2
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT:-8085}
    volumes:
      - ${DOCKER_VOLUMES_PATH}/qbittorrent:/config
      - ${DOCKER_VOLUMES_PATH}/qbittorrent/downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped
